### ISSUE TITLE
bro bank issue on depo pays and withdraw  when i try to depo pays or withdraws and this character 1000000000000000000000000000000000000000000000000000000000000000000000000000    server is crashing xd

### ISSUE THREAD

**Issue by Kelvincleon1234** [ElectroGamesDev/BankUI#32]

**Comment by ElectroGamesDev** [comment]
This is most likely because the number is greater than the integer's max value. I have no plans to fix this. There's almost no reason for a transaction to be this big anyways.

**Comment by Kelvincleon1234** [comment]
bro i know but i didnt have much money if players try to input a lot of character the server like can crashing can u fix pls because it is for high server

**Comment by Kelvincleon1234** [comment]
like make a code for imit the input?

**Comment by ElectroGamesDev** [comment]
Feel free to add the limit yourself and submit a pull request. I have no plans to update any of my plugins, even for small changes.

**Comment by Kelvincleon1234** [comment]
bro how to make the limi it i can code but i cant remake plugins i dont have much idea to remake

**Comment by ElectroGamesDev** [comment]
Hire a developer to add the limit. It should only take a few seconds to code.
